### PR TITLE
updating mastodon links and page

### LINKED ISSUE #33: Links on home page with other social media icons for Mastodon
I've gotten a complaint that someone went to the hpc.social site and didn't see "where to sign up". Should we put a link on home page with other social media icons for Mastodon site? The downside of this is that the other links are to individual administrative contact accounts, so it would be inconsistent to have a Mastodon icon that takes you to the site instead of to the admin contact. Still it would be better than nothing.

Perhaps we could add such an icon -- I looked but didn't see where the three that are there already are selected, though I did find a page of info for a bunch of social media providers that unfortunately did not list Mastodon, so haven't taken any action on this. 

If we wanted to be consistent we could add an iconized link like the others that send you to the [https://mast.hpc.social/@admin](https://mast.hpc.social/@admin) account page but put a text link to the Mastodon site About page, which includes links to sign in or create an account when not signed in already, with a label like [Join us on Mastodon](https://mast.hpc.social/about) for that link.

### LINKED ISSUE #36: Mastodon links page is redundant
See https://github.com/hpc-social/hpc-social.github.io/pull/34.

We should likely put the metadata we need in the mastodon page (that we retrieve live in the UI from the markdown) and remove the extra list of links at the top. otherwise we will need to maintain two things with redundant information, which is not ideal!

### PR DESCRIPTION
**Pull request by vsoch**
This will address a few issues:

 - fix #36 removing the extra verbosity from bringing in the GitHub readme and just linking to it
 - discussion from #38 to change the portal/home page to link the the Mastodon project page, where there is a big obvious "Join Us On Mastodon!" button
 - fix #33 adds the social media icon for Mastodon. Re-generating the font is tricky, but instead I am adding the svg directly as the right size and color (and hopefully this should work!)
 
The user flow (for someone that comes to the site looking to join Mastodon) could be either of the following:

- Click the icon to go directly there (new tab)
- Click "Mastodon" to go to the Mastodon page, and see the obvious button to join. 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
New icon isn't rendering in preview - taking a look.

**Comment by vsoch** [comment]
okay I see the issues - going to push a fix.

**Comment by vsoch** [comment]
Previews:

image
image

**Comment by alansill** [comment]
Previews in the PR look good. Out of curiosity, why doesn't the icon show up in the Netlify preview after the fix that made it work in the posted previews?

**Comment by vsoch** [comment]
The reason it didn't work for the first push was because the URL to provide the icon from the hpc.social domain doesn't exist yet. The fix uses a hard slash that will honor whatever root domain is provided (including the preview site). This should always work for the site here, and only will have issue if this template is moved to a subdomain site (e.g., like the map).

**Review by alansill — COMMENTED** [review]
I need to get better about doing reviews instead of just proceeding to the merge. I did look over the preview however and it looks good.

**Comment by vsoch** [comment]
Yeah! That's why I wanted to get Netlify previews up quickly - they make reviewing webby stuff really easy (and you don't necessarily need to look at the messy code if you know where on the site to look). I really love Netlify - I wish their free tier was larger I'd use it all over the place. We only get 300 builds / month.

Now that I think of it - when we merge, we are using up build time. I think what we will need to do moving forward is adding a `[skip ci]` to every PR as a squash and merge in the message, and that way it will skip. See https://answers.netlify.com/t/support-guide-how-can-i-optimize-my-netlify-build-time/3907/5 I can't find any global way to disable building the production branch.

**Pull request merged**
