### PR TITLE
adding start of chats spaces

### PR DESCRIPTION
**Pull request by vsoch**
we still need the complete discord information - I have only added slack. I'm also adding the new (dark background) dinosaur logo so it somewhat combines the dark branding of the text logo with the dinosaur (akin to the site).

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by Qeolvdxu** [comment]
> 

I rebranded the discord to fit HPC.social. Here is an invite link that is set never to expire: https://discord.gg/gKdmwMEesR

**Comment by vsoch** [comment]
Thank you @Qeolvdxu ! I'll add this to the PR. Are there any special instructions or notes you want to add?

**Comment by alansill** [comment]
Is the invite safe to post here?

**Comment by Qeolvdxu** [comment]
If the invite will be included on the website I don't see why it can't go here as well

> Is the invite safe to post here?

**Comment by alansill** [comment]
> If the invite will be included on the website I don't see why it can't go here as well
> 
> 
> 
> > Is the invite safe to post here?
> 
> 
> 
> 

Thanks, just checking.

**Comment by vsoch** [comment]
@alansill we are doing the same for slack - and if you read the page it’s a “we’re trying it out with a no tolerance policy.” If we start to see bots or the invite link used maliciously it will be disabled and removed. I’m watching slack and I’m sure @Qeolvdxu can watch discord.

**Comment by Qeolvdxu** [comment]
> Thank you @Qeolvdxu ! I'll add this to the PR. Are there any special instructions or notes you want to add?

There should not be a need for additional instructions, and there are rules with more information given to you once you join the discord. Will the Matrix and Discord be included in the contact icons at the bottom of the home page?

**Comment by vsoch** [comment]
@Qeolvdxu matrix is sort of having a tragedy of the commons at the moment, so I think for now we are just going to include Discord and slack.

**Comment by Qeolvdxu** [comment]
> 

Understandable. That should be everything from me then :)

**Comment by Qeolvdxu** [comment]
Looking at the preview, I noticed that the image used for the chat project is relatively low resolution compared to the other projects.

**Comment by vsoch** [comment]
yeah it's just a screen shot of a tiny space - I didn't have anything better atm. I have a stable diffusion server I use to make graphics but I haven't turned it on yet and it's.... over there (looks across the apartment). Too far. :laughing: If you'd like to make something better I'd be happy to add it here!

**Comment by Qeolvdxu** [comment]
i sent you an idea on slack :)

**Comment by vsoch** [comment]
Updated here - it's amazing! 
image

**Comment by alansill** [comment]
Any way to add the hpc.social logo icon?

**Comment by vsoch** [comment]
@alansill it's in his eye, it's an easter egg. ;) 

image

My 0.02 for these graphics is simplicity is best - so arbitrarily adding another logo (in a way that doesn't make sense) doesn't make sense to me. I think there is space for the two, but they should be scoped. E.g., the graphic dinosaur is for places that are intended to be fun and afford a graphic logo. the hpc.social might be for other places that need the name explicitly stated. I think we can use both of them as needed/wanted without artificially shoving them together.

My 0.02.

**Comment by alansill** [comment]
How about in the lower right corner of the card? There's lots of space there and I don't think it would distract.

**Comment by vsoch** [comment]
> How about in the lower right corner of the card? There's lots of space there and I don't think it would distract.

I'm -1 on that, I do think it's awkward and distracting. But I'll let @Qeolvdxu decide.

**Comment by Qeolvdxu** [comment]
> > How about in the lower right corner of the card? There's lots of space there and I don't think it would distract.
> 
> I'm -1 on that, I do think it's awkward and distracting. But I'll let @Qeolvdxu decide.
> 
> If you want to add something, I'd try some kind of watermark, meaning sort of a faded (slightly lighter version) of the current background but definitely not black.

Personally I didn't add it because it is not on most of the project images. I enjoy the simplicity of it now. The image is only being displayed on our own website so i thought a logo wouldn't be necessary, I only added the dino because I wanted someone to be speaking through a bubble.

**Comment by alansill** [comment]
I think the map page sets the standard. I think of the inverse icon as like a breadcrumb -- it should be present on every page of the web site somewhere. We can add it to the web pages themselves to avoid having to put it in cards, and certainly we can develop one with a different infill color if needed for certain settings, but there should be such an icon on every page of the project I believe to add cohesion. 

I'll merge this now for the sake of making progress, but think the dino logo should be used to add the "fun" element as you say, and as an invitation in to a new medium, and not as a complete replacement of the branding icon.

**Comment by vsoch** [comment]
@alansill this is not a page, it's a graphic on an existing site. The other images don't have it. So I think we can move forward striving to add the text one "somewhere" on the page but I think it's unreasonable to require it for any one-off graphic.

**Comment by vsoch** [comment]
And I'll also note your graphic is already on this page, and every page of the site, thus is meeting this standard.

image

**Comment by vsoch** [comment]
Thanks to you both! Really happy how this turned out (and looking forward to growing our chat community!)

**Comment by sramkrishna** [comment]
Are there any concerns on bifurcation of the community on different chat services? I'm not quite clear on the strategy? I assume we are trying to find the best fit between the various services.

**Comment by alansill** [comment]
Still experimenting. Directions will be set by experience.

**Comment by sramkrishna** [comment]
OK, makes sense. I'll see about a matrix demo as well - unless y'alls don't
want that. Let me know, I don't want to over complicate things by adding
more choice.

**Comment by vsoch** [comment]
I was holding off on matrix because of the recent news about how it's struggling (the article I saw on reddit mentioned it's a tragedy of the commons sort of thing). We actually did start a matrix space a few weeks back but maybe one person joined? So I think for now (unless there is huge push that people want to join and use it) I thought we could hold off. Of course happy to change that stance if/when presented with updated information!

**Comment by sramkrishna** [comment]
Yes, I saw that as well. The protocol and what not is fine but they had to
lay off folks working on element the main client. There are of course other
clients - I don't think there is a danger yet. I think the blog post was to
point out that matrix is the commons and people still need to invest in
them. Just like mastodon.

But if nobody is showing up that's a different problem. In this case, both
Slack and Discord have the network effect. We could just do irc ;-)

**Comment by alansill** [comment]
I think the main value of matrix might be in its ability to support bridges and other types of clients in addition to chat. In some sense it's not ideal that it doesn't just integrate with ActivityPub but they're very different protocols. For now let's see what happens with Slack and Discord. In some sense it doesn't matter if the community members who use them don't use the others, but it was really interesting to me to see that there was persistent interest in adding chat in addition to Mastodon. In principle there's also a separate HPC group still on Twitter also, but it looks to be really dormant and was not one of our projects. If it looks like the many problems with Twitter ever get solved, which doesn't seem to me to be likely, there's another option that could be explored to tie it in.

To be clear, starting another free space with Element or another Matrix app seems to me to have limited value unless we can add integration with other apps and/or bridging to simplify the community interactions. Right now I'd like to explore the uptake with Slack and Discord to see what happens. But that's just my opinion.

**Comment by sramkrishna** [comment]
The experience at least with irc <-> matrix bridge was the burden to
maintain them. Librechat is bridged to GNOME's matrix channels although
matrix is the primary while the irc hardliners stayed on librechat. GNOME
abandoned the irc server we had for 20+ years as it would require a lot of
updates to make it work with the bridge properly.

**Pull request merged**
