### PR TITLE
Add more detailed list of links

### PR DESCRIPTION
**Pull request by alansill**
Add more detailed list of links to the Mastodon project page, including direct account creation and invitation links, and improve formatting for these.

### CODE REVIEW

**Comment by vsoch** [comment]
We already had a lot of these links in the included policy page - it seems redundant and a bit too busy now:

image

**Comment by vsoch** [comment]
So two options - either put the additional links in that markdown in the policy readme (and remove these changes) or remove the included markdown. My suggestion is to do the first so we only have to maintain one thing :)

**Comment by alansill** [comment]
Hmm, the policies page was intended to be just a link from the HPC.social project. I don't think we actually need to render it onto that page on the main site, just link it. That factors off the policy portion as being in a place subject to community feedback on GitHub and we can concentrate on getting-started info on the Projects page. Note that the links given there are unlikely to change.

**Comment by vsoch** [comment]
Ah ok - maybe you can be more clear about this next time in an issue - my understanding was that you wanted the content to render verbatim into the page, and I spent a bit of time adding showdown.js and custom filtering to make that happen.

**Pull request merged**
