### PR TITLE
adding linked mastodon policy to Mastodon project page

### LINKED ISSUE #15: Links for hpc.social server policies
I have created a page for site policies in the hpc-social/mastodon-policies repository. Is there an easy way to transfer these pages into the main web site or should I make a new policies.hpc.social web destination for them? Incorporating them seems better.

### PR DESCRIPTION
**Pull request by vsoch**
This will close #15. It basically retrieves the content from the README of the mastodon-policies repository, does some tweaking for style / links working, and renders into the page:

image

@alansill do you think we could look into getting Netlify soon for previews? I have a free account but it doesn't have enough cycles to offer up to use here.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
Going to be a little cowboy and merge my own pull requests, since it's a small group of us, and it's easy to go back and make tweaks! Channeling @drcuff :laughing:

**Comment by alansill** [comment]
I'm trying to line up additional sponsors. With the commitment we have we can pay for the hosting and other related costs for about 6 months. Those per-user-per-month extra services like Netlify are not actually small compared with our overall hosting as we have taken some choices for economy and put most of the money into hosting costs, plus are relying on our sponsoring partners for services like email and (eventually) document generation to keep costs down.

**Comment by vsoch** [comment]
Is it not possible to set up netlify with a free account on an hpc.social alias? Perhaps if we have an hpc social bot (with an hpc.social email) account (that could do other automation too) the free netlify account could be linked to it?

**Comment by alansill** [comment]
Done! Check your hpc.social email.

**Pull request merged**
