### PR TITLE
Add community podcasts page

### LINKED ISSUE #40: Add Developer Stories as Project?
@alansill can we add the [Developer Stories](https://rseng.github.io/devstories/) podcast as a Project? I have featured many HPC community members and projects, and I think it could serve as a good voice for the community. If someone comes to the hpc.social site and wants to be interviewed, I'd love to have them! And also if you think / know of someone that would be a good guest, I can reach out to them too.

### PR DESCRIPTION
**Pull request by vsoch**
We should be able to support community podcasts, as a category of project! This adds the Developer Stories podcast (and I hope we can add others!) This will close #40 .

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by alansill** [comment]
Preview works and the page works. Ready to merge?

**Comment by vsoch** [comment]
Yep! And don’t forget the skip CI tag to save us a build!

**Comment by alansill** [comment]
> Preview works and the page works. Ready to merge?

I have once concern and that's that this page links to material off site and not controlled by our repositories. While I think this is okay, I think this lives in a space of "Other resources" Of maybe just "Resources" as a project. That page could for example have tabs for "Blogs", "Podcasts", and "Other Groups" that each give links to those types of resources. That would make it more clear that these are links to resources not hosted by hpc.social.

**Comment by vsoch** [comment]
It says clearly in the page that they are community maintained.

**Comment by alansill** [comment]
Merging... see also discussion under https://github.com/hpc-social/hpc-social.github.io/discussions/43 for more on this topic.

**Pull request merged**
